# Generated by Django 4.0.5 on 2022-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='nombre del producto')),
                ('price', models.FloatField(default=0.0, verbose_name='precio del producto')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock del producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
